### ISSUE TITLE
程序异常

### ISSUE THREAD

**Issue by david12-t** [PRaichu/xxqg#24]
Traceback (most recent call last):
  File "xuexi.py", line 114, in <module>
  File "xuexi.py", line 44, in run
  File "userOperation\check.py", line 51, in check_task
  File "selenium\webdriver\remote\webdriver.py", line 333, in get
  File "selenium\webdriver\remote\webdriver.py", line 321, in execute
  File "selenium\webdriver\remote\errorhandler.py", line 241, in check_response
selenium.common.exceptions.UnexpectedAlertPresentException: Alert Text: {Alert text :
Message: unexpected alert open: {Alert text : }
  (Session info: chrome=91.0.4472.77)

--> 程序异常，请尝试重启脚本

**Comment by PRaichu** [comment]
> Traceback (most recent call last):
> File "xuexi.py", line 114, in
> File "xuexi.py", line 44, in run
> File "userOperation\check.py", line 51, in check_task
> File "selenium\webdriver\remote\webdriver.py", line 333, in get
> File "selenium\webdriver\remote\webdriver.py", line 321, in execute
> File "selenium\webdriver\remote\errorhandler.py", line 241, in check_response
> selenium.common.exceptions.UnexpectedAlertPresentException: Alert Text: {Alert text :
> Message: unexpected alert open: {Alert text : }
> (Session info: chrome=91.0.4472.77)
> 
> --> 程序异常，请尝试重启脚本

感谢反馈！
这个问题是不是重复出现，有没有当时浏览器的截图，麻烦描述一下出现问题的过程，我才好去排查bug，谢谢

**Comment by david12-t** [comment]
> > Traceback (most recent call last):
> > File "xuexi.py", line 114, in
> > File "xuexi.py", line 44, in run
> > File "userOperation\check.py", line 51, in check_task
> > File "selenium\webdriver\remote\webdriver.py", line 333, in get
> > File "selenium\webdriver\remote\webdriver.py", line 321, in execute
> > File "selenium\webdriver\remote\errorhandler.py", line 241, in check_response
> > selenium.common.exceptions.UnexpectedAlertPresentException: Alert Text: {Alert text :
> > Message: unexpected alert open: {Alert text : }
> > (Session info: chrome=91.0.4472.77)
> > --> 程序异常，请尝试重启脚本
> 
> 感谢反馈！
> 这个问题是不是重复出现，有没有当时浏览器的截图，麻烦描述一下出现问题的过程，我才好去排查bug，谢谢

今天没看到，下次我再留意，非常感谢！

**Comment by PRaichu** [comment]
> 今天没看到，下次我再留意，非常感谢！

感谢反馈！
