### ISSUE TITLE
最新版本 Win10报错 无法启动

### ISSUE THREAD

**Issue by StubbornYang** [PRaichu/xxqg#27]
Traceback (most recent call last):
  File "urllib3\connectionpool.py", line 696, in urlopen
  File "urllib3\connectionpool.py", line 964, in _prepare_proxy
  File "urllib3\connection.py", line 359, in connect
  File "urllib3\connection.py", line 496, in _connect_tls_proxy
  File "urllib3\util\ssl_.py", line 432, in ssl_wrap_socket
  File "urllib3\util\ssl_.py", line 474, in _ssl_wrap_socket_impl
  File "ssl.py", line 500, in wrap_socket
  File "ssl.py", line 1040, in _create
  File "ssl.py", line 1309, in do_handshake
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:1122)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "requests\adapters.py", line 439, in send
  File "urllib3\connectionpool.py", line 755, in urlopen
  File "urllib3\util\retry.py", line 573, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.xuexi.cn', port=443): Max retries exceeded with url: /lgdata/u1ght1omn2.json (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1122)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "xuexi.py", line 110, in <module>
  File "getData\get_article.py", line 18, in get_article
  File "requests\api.py", line 76, in get
  File "requests\api.py", line 61, in request
  File "requests\sessions.py", line 542, in request
  File "requests\sessions.py", line 655, in send
  File "requests\adapters.py", line 514, in send
requests.exceptions.SSLError: HTTPSConnectionPool(host='www.xuexi.cn', port=443): Max retries exceeded with url: /lgdata/u1ght1omn2.json (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1122)')))

--> 程序异常，请尝试重启脚本

      __/\\\\\\\\\\\\\____/\\\________/\\\__________/\\\\\\\\\\\\__/\\\\\\\\\\\\_____/\\\\\\\\\\\\\\\_
       _\/\\\/////////\\\_\///\\\____/\\\/_________/\\\//////////__\/\\\////////\\\__\/\\\///////////__
        _\/\\\_______\/\\\___\///\\\/\\\/__________/\\\_____________\/\\\______\//\\\_\/\\\_____________
         _\/\\\\\\\\\\\\\\______\///\\\/___________\/\\\____/\\\\\\\_\/\\\_______\/\\\_\/\\\\\\\\\\\_____
          _\/\\\/////////\\\_______\/\\\____________\/\\\___\/////\\\_\/\\\_______\/\\\_\/\\\///////______
           _\/\\\_______\/\\\_______\/\\\____________\/\\\_______\/\\\_\/\\\_______\/\\\_\/\\\_____________
            _\/\\\_______\/\\\_______\/\\\____________\/\\\_______\/\\\_\/\\\_______/\\\__\/\\\_____________
             _\/\\\\\\\\\\\\\/________\/\\\____________\//\\\\\\\\\\\\/__\/\\\\\\\\\\\\/___\/\\\_____________
              _\/////////////__________\///______________\////////////____\////////////_____\///______________

请按任意键继续. . .

**Comment by PRaichu** [comment]
> Traceback (most recent call last):
> File "urllib3\connectionpool.py", line 696, in urlopen
> File "urllib3\connectionpool.py", line 964, in _prepare_proxy File "urllib3\connection.py", line 359, in connect File "urllib3\connection.py", line 496, in _connect_tls_proxy File "urllib3\util\ssl_.py", line 432, in ssl_wrap_socket File "urllib3\util\ssl_.py", line 474, in _ssl_wrap_socket_impl
> File "ssl.py", line 500, in wrap_socket
> File "ssl.py", line 1040, in _create
> File "ssl.py", line 1309, in do_handshake
> ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:1122)
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
> File "requests\adapters.py", line 439, in send
> File "urllib3\connectionpool.py", line 755, in urlopen
> File "urllib3\util\retry.py", line 573, in increment
> urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.xuexi.cn', port=443): Max retries exceeded with url: /lgdata/u1ght1omn2.json (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1122)')))
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
> File "xuexi.py", line 110, in
> File "getData\get_article.py", line 18, in get_article
> File "requests\api.py", line 76, in get
> File "requests\api.py", line 61, in request
> File "requests\sessions.py", line 542, in request
> File "requests\sessions.py", line 655, in send
> File "requests\adapters.py", line 514, in send
> requests.exceptions.SSLError: HTTPSConnectionPool(host='www.xuexi.cn', port=443): Max retries exceeded with url: /lgdata/u1ght1omn2.json (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1122)')))
> 
> --> 程序异常，请尝试重启脚本
> 
> ```
>   __/\\\\\\\\\\\\\____/\\\________/\\\__________/\\\\\\\\\\\\__/\\\\\\\\\\\\_____/\\\\\\\\\\\\\\\_
>    _\/\\\/////////\\\_\///\\\____/\\\/_________/\\\//////////__\/\\\////////\\\__\/\\\///////////__
>     _\/\\\_______\/\\\___\///\\\/\\\/__________/\\\_____________\/\\\______\//\\\_\/\\\_____________
>      _\/\\\\\\\\\\\\\\______\///\\\/___________\/\\\____/\\\\\\\_\/\\\_______\/\\\_\/\\\\\\\\\\\_____
>       _\/\\\/////////\\\_______\/\\\____________\/\\\___\/////\\\_\/\\\_______\/\\\_\/\\\///////______
>        _\/\\\_______\/\\\_______\/\\\____________\/\\\_______\/\\\_\/\\\_______\/\\\_\/\\\_____________
>         _\/\\\_______\/\\\_______\/\\\____________\/\\\_______\/\\\_\/\\\_______/\\\__\/\\\_____________
>          _\/\\\\\\\\\\\\\/________\/\\\____________\//\\\\\\\\\\\\/__\/\\\\\\\\\\\\/___\/\\\_____________
>           _\/////////////__________\///______________\////////////____\////////////_____\///______________
> ```
> 
> 请按任意键继续. . .



> Traceback (most recent call last):
> File "urllib3\connectionpool.py", line 696, in urlopen
> File "urllib3\connectionpool.py", line 964, in _prepare_proxy File "urllib3\connection.py", line 359, in connect File "urllib3\connection.py", line 496, in _connect_tls_proxy File "urllib3\util\ssl_.py", line 432, in ssl_wrap_socket File "urllib3\util\ssl_.py", line 474, in _ssl_wrap_socket_impl
> File "ssl.py", line 500, in wrap_socket
> File "ssl.py", line 1040, in _create
> File "ssl.py", line 1309, in do_handshake
> ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:1122)
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
> File "requests\adapters.py", line 439, in send
> File "urllib3\connectionpool.py", line 755, in urlopen
> File "urllib3\util\retry.py", line 573, in increment
> urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.xuexi.cn', port=443): Max retries exceeded with url: /lgdata/u1ght1omn2.json (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1122)')))
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
> File "xuexi.py", line 110, in
> File "getData\get_article.py", line 18, in get_article
> File "requests\api.py", line 76, in get
> File "requests\api.py", line 61, in request
> File "requests\sessions.py", line 542, in request
> File "requests\sessions.py", line 655, in send
> File "requests\adapters.py", line 514, in send
> requests.exceptions.SSLError: HTTPSConnectionPool(host='www.xuexi.cn', port=443): Max retries exceeded with url: /lgdata/u1ght1omn2.json (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1122)')))
> 
> --> 程序异常，请尝试重启脚本
> 
> ```
>   __/\\\\\\\\\\\\\____/\\\________/\\\__________/\\\\\\\\\\\\__/\\\\\\\\\\\\_____/\\\\\\\\\\\\\\\_
>    _\/\\\/////////\\\_\///\\\____/\\\/_________/\\\//////////__\/\\\////////\\\__\/\\\///////////__
>     _\/\\\_______\/\\\___\///\\\/\\\/__________/\\\_____________\/\\\______\//\\\_\/\\\_____________
>      _\/\\\\\\\\\\\\\\______\///\\\/___________\/\\\____/\\\\\\\_\/\\\_______\/\\\_\/\\\\\\\\\\\_____
>       _\/\\\/////////\\\_______\/\\\____________\/\\\___\/////\\\_\/\\\_______\/\\\_\/\\\///////______
>        _\/\\\_______\/\\\_______\/\\\____________\/\\\_______\/\\\_\/\\\_______\/\\\_\/\\\_____________
>         _\/\\\_______\/\\\_______\/\\\____________\/\\\_______\/\\\_\/\\\_______/\\\__\/\\\_____________
>          _\/\\\\\\\\\\\\\/________\/\\\____________\//\\\\\\\\\\\\/__\/\\\\\\\\\\\\/___\/\\\_____________
>           _\/////////////__________\///______________\////////////____\////////////_____\///______________
> ```
> 
> 请按任意键继续. . .

感谢反馈，请检查是否开启了VPN或者其他代理软件，关闭后再试试

**Comment by Michael-C-H** [comment]
我开了代理，就是这个错，建议大佬 @PRaichu 备注一下不能开代理，或者开放配置文件支持配置代理
