### ISSUE TITLE
1.0.6版本答题报错

### ISSUE THREAD

**Issue by ChinaMobile5G** [PRaichu/xxqg#29]
Traceback (most recent call last):
  File "xuexi.py", line 114, in <module>
  File "xuexi.py", line 44, in run
  File "userOperation\check.py", line 51, in check_task
  File "selenium\webdriver\remote\webdriver.py", line 333, in get
  File "selenium\webdriver\remote\webdriver.py", line 321, in execute
  File "selenium\webdriver\remote\errorhandler.py", line 241, in check_response
selenium.common.exceptions.UnexpectedAlertPresentException: Alert Text: {Alert text :
Message: unexpected alert open: {Alert text : }
  (Session info: chrome=91.0.4472.77)

**Comment by ChinaMobile5G** [comment]
1.0.7直接闪退.........  怎么办大佬...

**Comment by PRaichu** [comment]
> Traceback (most recent call last):
> File "xuexi.py", line 114, in
> File "xuexi.py", line 44, in run
> File "userOperation\check.py", line 51, in check_task
> File "selenium\webdriver\remote\webdriver.py", line 333, in get
> File "selenium\webdriver\remote\webdriver.py", line 321, in execute
> File "selenium\webdriver\remote\errorhandler.py", line 241, in check_response
> selenium.common.exceptions.UnexpectedAlertPresentException: Alert Text: {Alert text :
> Message: unexpected alert open: {Alert text : }
> (Session info: chrome=91.0.4472.77)

感谢反馈，这个问题已经在解决的路上了，近期应该会更新修复

**Comment by PRaichu** [comment]
> 1.0.7直接闪退......... 怎么办大佬...

闪退的过程能具体描述一下吗，比如在什么页面闪退的，在什么情况下闪退的
