### ISSUE TITLE
当前版本:1.0.8.1 保错

### ISSUE THREAD

**Issue by solife2020** [PRaichu/xxqg#34]
Traceback (most recent call last):
  File "xuexi.py", line 113, in <module>
  File "custom\xuexi_chrome.py", line 10, in __init__
  File "selenium\webdriver\chrome\webdriver.py", line 76, in __init__
  File "selenium\webdriver\remote\webdriver.py", line 157, in __init__
  File "selenium\webdriver\remote\webdriver.py", line 252, in start_session
  File "selenium\webdriver\remote\webdriver.py", line 321, in execute
  File "selenium\webdriver\remote\errorhandler.py", line 242, in check_response
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot find Chrome binary

--> 程序异常，请尝试重启脚本
--> 当前版本:1.0.8.1
请按任意键继续. . .

**Comment by solife2020** [comment]
编译好的版本运行提示这个
