### ISSUE TITLE
学习强国V1.0.8.1报错，不知道如何解决？

### ISSUE THREAD

**Issue by 46161971** [PRaichu/xxqg#36]
![image](https://user-images.githubusercontent.com/26788078/121496812-56192f80-c9ca-11eb-870a-b82f3c1a540d.png) 
exe文件执行，如图计算机丢失api-ms-win-croe-path-l1-1-0.dll。py代码运行，报错== RESTART: C:\Users\Administrator\Desktop\xxqg-master(1)\xxqg-master\xuexi.py =
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\xxqg-master(1)\xxqg-master\operation\get_chromedriver.py", line 13, in do
    version = get_version(program_path)
  File "C:\Users\Administrator\Desktop\xxqg-master(1)\xxqg-master\operation\get_chromedriver.py", line 66, in get_version
    return version_info.split(' ')[1]
IndexError: list index out of range

--> 程序异常，请确保你的chrome浏览器是最新版本，然后重启脚本

**Comment by wanwanBAQ** [comment]
下载一个dx修复工具，或者微软运行库

**Comment by PRaichu** [comment]
> 下载一个dx修复工具，或者微软运行库

@46161971  这是你系统环境的问题，试试上面 @wanwanBAQ  的方法
