### ISSUE TITLE
1.0.8.2打开以后报错

### ISSUE THREAD

**Issue by wlipei** [PRaichu/xxqg#48]
Traceback (most recent call last):
  File "operation\check_version.py", line 14, in get_latest_version
  File "requests\api.py", line 75, in get
  File "requests\api.py", line 61, in request
  File "requests\sessions.py", line 542, in request
  File "requests\sessions.py", line 655, in send
  File "requests\adapters.py", line 449, in send
  File "urllib3\connectionpool.py", line 696, in urlopen
  File "urllib3\connectionpool.py", line 964, in _prepare_proxy
  File "urllib3\connection.py", line 359, in connect
  File "urllib3\connection.py", line 506, in _connect_tls_proxy
  File "urllib3\util\ssl_.py", line 453, in ssl_wrap_socket
  File "urllib3\util\ssl_.py", line 495, in _ssl_wrap_socket_impl
  File "ssl.py", line 407, in wrap_socket
  File "ssl.py", line 773, in __init__
ValueError: check_hostname requires server_hostname

--> 请求版本号失败，请检查是否开启了VPN或代理软件，如果开启了请关闭后再试
--> 此处报错为版本号请求失败，不会影响程序运行，无需关闭程序

**Comment by wlipei** [comment]
平台是Windows 10 X64位
谷歌浏览器是最新版的。

**Comment by PRaichu** [comment]
这种情况可能是你系统环境的问题

**Comment by wlipei** [comment]
嗯，我已经重新安装了系统在来试试。还是多谢大神开发这么好用的软件。




------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;; 
Date: 2021年9月3日(星期五) 上午9:58
To: ***@***.***&gt;; 
Cc: ***@***.***&gt;; ***@***.***&gt;; 
Subject: Re: [PRaichu/xxqg] 1.0.8.2打开以后报错 (#48)





 
这种情况可能是你系统环境的问题
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
