### ISSUE TITLE
当前版本:1.0.8.2 程序异常，请尝试重启脚本

### ISSUE THREAD

**Issue by 1020329667** [PRaichu/xxqg#49]
Traceback (most recent call last):
  File "xuexi.py", line 134, in <module>
  File "xuexi.py", line 36, in user_login
  File "userOperation\login.py", line 17, in login
  File "selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
  File "selenium\webdriver\remote\webdriver.py", line 978, in find_element
  File "selenium\webdriver\remote\webdriver.py", line 321, in execute
  File "selenium\webdriver\remote\errorhandler.py", line 242, in check_response
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"/html/body/div/div/div[1]"}
  (Session info: chrome=93.0.4577.63)

--> 程序异常，请尝试重启脚本
--> 当前版本:1.0.8.2

**Comment by PRaichu** [comment]
感谢反馈，已发布 [1.0.8.3](https://github.com/PRaichu/xxqg/releases/tag/1.0.8.3) 更新，可以试试这个版本
