### ISSUE TITLE
1.0.8.3 程序异常

### ISSUE THREAD

**Issue by ChinaMobile5G** [PRaichu/xxqg#51]
Traceback (most recent call last):
  File "xuexi.py", line 113, in <module>
  File "custom\xuexi_chrome.py", line 14, in __init__
  File "selenium\webdriver\chrome\webdriver.py", line 81, in __init__
  File "selenium\webdriver\remote\webdriver.py", line 157, in __init__
  File "selenium\webdriver\remote\webdriver.py", line 252, in start_session
  File "selenium\webdriver\remote\webdriver.py", line 321, in execute
  File "selenium\webdriver\remote\errorhandler.py", line 242, in check_response
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 94
Current browser version is 93.0.4577.63 with binary path C:\Program Files\Google\Chrome\Application\chrome.exe

--> 程序异常，请尝试重启脚本
--> 当前版本:1.0.8.3
请按任意键继续. . .                                              2021-9-9

                                                       

--> 程序当前版本号：1.0.8.2，最新版本号：1.0.8.3，该版本可能已过时，建议下载最新版本以获得更好的体验！
--> 下载地址：https://github.com/PRaichu/xxqg/releases/latest
--> 当然，你也可以选择不更新，这不会影响当前程序的使用！

Traceback (most recent call last):
  File "xuexi.py", line 113, in <module>
  File "custom\xuexi_chrome.py", line 11, in __init__
  File "selenium\webdriver\chrome\webdriver.py", line 81, in __init__
  File "selenium\webdriver\remote\webdriver.py", line 157, in __init__
  File "selenium\webdriver\remote\webdriver.py", line 252, in start_session
  File "selenium\webdriver\remote\webdriver.py", line 321, in execute
  File "selenium\webdriver\remote\errorhandler.py", line 242, in check_response
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 94
Current browser version is 93.0.4577.63 with binary path C:\Program Files\Google\Chrome\Application\chrome.exe

--> 程序异常，请尝试重启脚本
--> 当前版本:1.0.8.2
请按任意键继续. . .                                    2021-9-9

**Comment by PRaichu** [comment]
感谢反馈，分析发现这是淘宝镜像的chromedriver版本更新比chrome浏览器正式版本更新要快，导致chromedriver已经更新到最新版，但是chrome浏览器还没发布更新，造成驱动版本不匹配，目前只能等chrome发布更新。我会尽快发布修复更新，以匹配低版本的chrome浏览器

**Comment by adamnb1** [comment]
大佬啊，这个chromedriver能不能让我们选择是否更新，或者单位弄个工具更新，哪怕给个地址让我们手动更新。这也比强制更新好使啊。

**Comment by fortunelee** [comment]
大佬啊，那个读文章的那个能不能优化下，有的看不够1分钟的不计积分的

**Comment by PRaichu** [comment]
> 大佬啊，这个chromedriver能不能让我们选择是否更新，或者单位弄个工具更新，哪怕给个地址让我们手动更新。这也比强制更新好使啊。

感谢反馈，其实使用过程中，大部分人都是不会自己更新chromedriver的，就是考虑到这个才加上自动更新的功能，这次更新我会在设置中加上这个配置项，让用户决定是否需要自动更新驱动

**Comment by PRaichu** [comment]
> 大佬啊，那个读文章的那个能不能优化下，有的看不够1分钟的不计积分的

感谢反馈，目前看文章的机制就是随机浏览65-75秒，按理来说基本上不会出现不给分的情况，如果多次出现不计分的情况，请考虑一下自己账号是不是被监测了，本次更新我将会适当加长浏览时间，如果之后还是多次出现此问题，建议停止一段时间使用此脚本，确保账号安全

**Comment by waterun** [comment]
我自己改了一下，不用最新版本的driver，而是匹配当前安装的chrome版本，只要不是太老的chrome版本，没必要匹配最新

**Comment by adamnb1** [comment]
> 我自己改了一下，不用最新版本的driver，而是匹配当前安装的chrome版本，只要不是太老的chrome版本，没必要匹配最新
> ![get_latest_version](https://user-images.githubusercontent.com/13463811/132788087-0cd87f4d-0a82-4c07-b608-402e3470296c.jpg)

python编译不会啊，也没配置python环境，一直用的exe。老白，没办法。

**Comment by adamnb1** [comment]
> > 我自己改了一下，不用最新版本的driver，而是匹配当前安装的chrome版本，只要不是太老的chrome版本，没必要匹配最新
> > ![get_latest_version](https://user-images.githubusercontent.com/13463811/132788087-0cd87f4d-0a82-4c07-b608-402e3470296c.jpg)
> 
> python编译不会啊，也没配置python环境，一直用的exe。老白，没办法。

能不能编译一下，发上来分享一下？

**Comment by orlando-95** [comment]
我刚刚还在傻乎乎的找有没有chrome94呢

**Comment by waterun** [comment]
> > > 我自己改了一下，不用最新版本的driver，而是匹配当前安装的chrome版本，只要不是太老的chrome版本，没必要匹配最新
> > > ![get_latest_version](https://user-images.githubusercontent.com/13463811/132788087-0cd87f4d-0a82-4c07-b608-402e3470296c.jpg)
> > 
> > 
> > python编译不会啊，也没配置python环境，一直用的exe。老白，没办法。
> 
> 能不能编译一下，发上来分享一下？

等作者更新吧，应该很快的。我改动很多，包括本地题库搜索等，不太方便上传。

**Comment by PRaichu** [comment]
已发布[1.0.9.0](https://github.com/PRaichu/xxqg/releases/tag/1.0.9.0)更新，欢迎更新使用！
