### ISSUE TITLE
版本1.0.9.0  浏览器已经是最高版本  报错

### ISSUE THREAD

**Issue by caolala** [PRaichu/xxqg#65]
--> 当前ChromeDriver版本号和Chrome浏览器版本号不一致，准备进行更新
Traceback (most recent call last):
  File "operation\get_chromedriver.py", line 29, in do
  File "operation\get_chromedriver.py", line 56, in get_download_version
IndexError: list index out of range

--> 程序异常，请确保你的chrome浏览器是最新版本，然后重启脚本
请按任意键继续. . .

**Comment by xiao911** [comment]
我也遇到了这个问题，研究了一下发现还是chromedriver版本的问题，去看一下自己chrome的版本号，再去下个对应版本的chromedrive替换掉文件夹里的那个就行了

**Comment by Sunk-Today** [comment]
> 我也遇到了这个问题，研究了一下发现还是chromedriver版本的问题，去看一下自己chrome的版本号，再去下个对应版本的chromedrive替换掉文件夹里的那个就行了

的确可以了，谢谢你！

**Comment by PRaichu** [comment]
感谢反馈，问题已修复，请下载最新版使用！
https://github.com/PRaichu/xxqg/releases/tag/1.0.9.1
