### ISSUE TITLE
浏览器窗口最大化情况下答题进行到视频答题会报错

### ISSUE THREAD

**Issue by rabuholikku** [PRaichu/xxqg#66]
每次进行到有视频答题就会容易报错，浏览器窗口已经最大化，并且是在前台不是在后台。还是会报element click intercepted。另外重启后有时能够解决，有时不能。

Traceback (most recent call last):
  File "operation\exam.py", line 149, in run_exam
  File "selenium\webdriver\remote\webelement.py", line 80, in click
  File "selenium\webdriver\remote\webelement.py", line 633, in _execute
  File "selenium\webdriver\remote\webdriver.py", line 321, in execute
  File "selenium\webdriver\remote\errorhandler.py", line 242, in check_response
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element is not clickable at point (1015, 753)
  (Session info: chrome=96.0.4664.110)

--> 答题异常，正在重试
--> 答题结束
Traceback (most recent call last):
  File "xuexi.py", line 136, in <module>
  File "xuexi.py", line 48, in run
  File "userOperation\check.py", line 50, in check_task
  File "custom\xuexi_chrome.py", line 31, in xuexi_get
  File "selenium\webdriver\chrome\webdriver.py", line 145, in execute_cdp_cmd
  File "selenium\webdriver\remote\webdriver.py", line 321, in execute
  File "selenium\webdriver\remote\errorhandler.py", line 241, in check_response
selenium.common.exceptions.UnexpectedAlertPresentException: Alert Text: {Alert text :
Message: unexpected alert open: {Alert text : }
  (Session info: chrome=96.0.4664.110)

**Comment by PRaichu** [comment]
感谢反馈，这个问题我也注意到了，之后会排查问题尽快解决！
