### ISSUE TITLE
1.0.9.1登录扫码后报错

### ISSUE THREAD

**Issue by rabuholikku** [PRaichu/xxqg#74]
扫码后报错，连续两次登录都报同样的错误。第三次登录正常。偶尔会出现这个错误。

--> 请在5分钟内扫码完成登录
Traceback (most recent call last):
  File "xuexi.py", line 134, in <module>
  File "xuexi.py", line 36, in user_login
  File "userOperation\login.py", line 16, in login
  File "selenium\webdriver\remote\webdriver.py", line 473, in find_element_by_id
  File "selenium\webdriver\remote\webdriver.py", line 1248, in find_element
  File "selenium\webdriver\remote\webdriver.py", line 425, in execute
  File "selenium\webdriver\remote\errorhandler.py", line 247, in check_response
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[id="qglogin"]"}
  (Session info: chrome=96.0.4664.110)
Stacktrace:
Backtrace:
        Ordinal0 [0x00986903+2517251]
        Ordinal0 [0x0091F8E1+2095329]
        Ordinal0 [0x00822848+1058888]
        Ordinal0 [0x0084D448+1233992]
        Ordinal0 [0x0084D63B+1234491]
        Ordinal0 [0x00877812+1406994]
        Ordinal0 [0x0086650A+1336586]
        Ordinal0 [0x00875BBF+1399743]
        Ordinal0 [0x0086639B+1336219]
        Ordinal0 [0x008427A7+1189799]
        Ordinal0 [0x00843609+1193481]
        GetHandleVerifier [0x00B15904+1577972]
        GetHandleVerifier [0x00BC0B97+2279047]
        GetHandleVerifier [0x00A16D09+534521]
        GetHandleVerifier [0x00A15DB9+530601]
        Ordinal0 [0x00924FF9+2117625]
        Ordinal0 [0x009298A8+2136232]
        Ordinal0 [0x009299E2+2136546]
        Ordinal0 [0x00933541+2176321]
        BaseThreadInitThunk [0x7793FA29+25]
        RtlGetAppContainerNamedObjectPath [0x77B67A9E+286]
        RtlGetAppContainerNamedObjectPath [0x77B67A6E+238]

**Comment by LXT2017** [comment]
这个bug是你登录太急了，你要等程序自己跳转到登录二维码窗口在扫描
