### ISSUE TITLE
程序异常，请尝试重启脚本

### ISSUE THREAD

**Issue by 1126001065** [PRaichu/xxqg#85]
![图片](https://user-images.githubusercontent.com/26452526/181222710-b33e8b03-f864-47c9-84b7-071890914fec.jpg)

**Comment by 670555467** [comment]
解决了吗

**Comment by blackdarks** [comment]
我也是这个情况啊，一运行就报错

**Comment by LLK0723** [comment]
我也是，怎么弄

**Comment by LLK0723** [comment]
Traceback (most recent call last):
  File "urllib3\connectionpool.py", line 700, in urlopen
  File "urllib3\connectionpool.py", line 994, in _prepare_proxy
  File "urllib3\connection.py", line 364, in connect
  File "urllib3\connection.py", line 501, in _connect_tls_proxy
  File "urllib3\util\ssl_.py", line 453, in ssl_wrap_socket
  File "urllib3\util\ssl_.py", line 495, in _ssl_wrap_socket_impl
  File "ssl.py", line 500, in wrap_socket
  File "ssl.py", line 1040, in _create
  File "ssl.py", line 1309, in do_handshake
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:1129)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "requests\adapters.py", line 440, in send
  File "urllib3\connectionpool.py", line 785, in urlopen
  File "urllib3\util\retry.py", line 592, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/PRaichu/xxqg/releases/latest (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "operation\check_version.py", line 14, in get_latest_version
  File "requests\api.py", line 75, in get
  File "requests\api.py", line 61, in request
  File "requests\sessions.py", line 529, in request
  File "requests\sessions.py", line 645, in send
  File "requests\adapters.py", line 517, in send
requests.exceptions.SSLError: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/PRaichu/xxqg/releases/latest (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)')))

--> 请求版本号失败，请检查你的网络环境
--> 此处报错为版本号请求失败，不会影响程序运行，无需关闭程序
Traceback (most recent call last):
  File "xuexi.py", line 113, in <module>
  File "custom\xuexi_chrome.py", line 15, in __init__
  File "selenium\webdriver\chrome\webdriver.py", line 70, in __init__
  File "selenium\webdriver\chromium\webdriver.py", line 93, in __init__
  File "selenium\webdriver\remote\webdriver.py", line 269, in __init__
  File "selenium\webdriver\remote\webdriver.py", line 360, in start_session
  File "selenium\webdriver\remote\webdriver.py", line 425, in execute
  File "selenium\webdriver\remote\errorhandler.py", line 247, in check_response
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot find Chrome binary
Stacktrace:
Backtrace:
        Ordinal0 [0x00946463+2188387]
        Ordinal0 [0x008DE461+1762401]
        Ordinal0 [0x007F3D78+802168]
        Ordinal0 [0x0080FDFE+916990]
        Ordinal0 [0x0080E331+910129]
        Ordinal0 [0x00841430+1119280]
        Ordinal0 [0x0084108A+1118346]
        Ordinal0 [0x0083C5F6+1099254]
        Ordinal0 [0x00816BE0+945120]
        Ordinal0 [0x00817AD6+948950]
        GetHandleVerifier [0x00BE71F2+2712546]
        GetHandleVerifier [0x00BD886D+2652765]
        GetHandleVerifier [0x009D002A+520730]
        GetHandleVerifier [0x009CEE06+516086]
        Ordinal0 [0x008E468B+1787531]
        Ordinal0 [0x008E8E88+1805960]
        Ordinal0 [0x008E8F75+1806197]
        Ordinal0 [0x008F1DF1+1842673]
        BaseThreadInitThunk [0x76716739+25]
        RtlGetFullPathName_UEx [0x776F8FEF+1215]
        RtlGetFullPathName_UEx [0x776F8FBD+1165]


--> 程序异常，请尝试重启脚本
--> 当前版本:1.0.9.2
请按任意键继续. . .

**Comment by 670555467** [comment]
> 
重新下载
