### ISSUE TITLE
启动异常

### ISSUE THREAD

**Issue by zhangyou1010** [PRaichu/xxqg#88]
Traceback (most recent call last):
  File "xuexi.py", line 134, in <module>
  File "xuexi.py", line 36, in user_login
  File "userOperation\login.py", line 17, in login
  File "selenium\webdriver\remote\webdriver.py", line 1248, in find_element
  File "selenium\webdriver\remote\webdriver.py", line 425, in execute
  File "selenium\webdriver\remote\errorhandler.py", line 247, in check_response
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[id="qglogin"]"}
  (Session info: chrome=104.0.5112.102)
Stacktrace:
Backtrace:
        Ordinal0 [0x009978B3+2193587]
        Ordinal0 [0x00930681+1771137]
        Ordinal0 [0x008441A8+803240]
        Ordinal0 [0x008724A0+992416]
        Ordinal0 [0x0087273B+993083]
        Ordinal0 [0x0089F7C2+1177538]
        Ordinal0 [0x0088D7F4+1103860]
        Ordinal0 [0x0089DAE2+1170146]
        Ordinal0 [0x0088D5C6+1103302]
        Ordinal0 [0x008677E0+948192]
        Ordinal0 [0x008686E6+952038]
        GetHandleVerifier [0x00C40CB2+2738370]
        GetHandleVerifier [0x00C321B8+2678216]
        GetHandleVerifier [0x00A217AA+512954]
        GetHandleVerifier [0x00A20856+509030]
        Ordinal0 [0x0093743B+1799227]
        Ordinal0 [0x0093BB68+1817448]
        Ordinal0 [0x0093BC55+1817685]
        Ordinal0 [0x00945230+1856048]
        BaseThreadInitThunk [0x7643FA29+25]
        RtlGetAppContainerNamedObjectPath [0x774B7A9E+286]
        RtlGetAppContainerNamedObjectPath [0x774B7A6E+238]

--> 程序异常，请尝试重启脚本
--> 当前版本:1.0.9.2

**Comment by zhangyou1010** [comment]
关掉自动更新后，可以了。
