### ISSUE TITLE
 程序异常，请尝试重启脚本

### ISSUE THREAD

**Issue by Forkey2023** [PRaichu/xxqg#93]
--> 程序当前版本号：1.0.9.1，最新版本号：1.0.9.2，该版本可能已过时，建议下载最新版本以获得更好的体验！
--> 下载地址：https://github.com/PRaichu/xxqg/releases/latest
--> 当然，你也可以选择不更新，这不会影响当前程序的使用！

--> 请在5分钟内扫码完成登录
--> 登录成功
Traceback (most recent call last):
  File "xuexi.py", line 136, in <module>
  File "xuexi.py", line 48, in run
  File "userOperation\check.py", line 74, in check_task
IndexError: list index out of range

--> 程序异常，请尝试重启脚本
--> 当前版本:1.0.9.1

      __/\\\\\\\\\\\\\____/\\\________/\\\__________/\\\\\\\\\\\\__/\\\\\\\\\\\\_____/\\\\\\\\\\\\\\\_
       _\/\\\/////////\\\_\///\\\____/\\\/_________/\\\//////////__\/\\\////////\\\__\/\\\///////////__
        _\/\\\_______\/\\\___\///\\\/\\\/__________/\\\_____________\/\\\______\//\\\_\/\\\_____________
         _\/\\\\\\\\\\\\\\______\///\\\/___________\/\\\____/\\\\\\\_\/\\\_______\/\\\_\/\\\\\\\\\\\_____
          _\/\\\/////////\\\_______\/\\\____________\/\\\___\/////\\\_\/\\\_______\/\\\_\/\\\///////______
           _\/\\\_______\/\\\_______\/\\\____________\/\\\_______\/\\\_\/\\\_______\/\\\_\/\\\_____________
            _\/\\\_______\/\\\_______\/\\\____________\/\\\_______\/\\\_\/\\\_______/\\\__\/\\\_____________
             _\/\\\\\\\\\\\\\/________\/\\\____________\//\\\\\\\\\\\\/__\/\\\\\\\\\\\\/___\/\\\_____________
              _\/////////////__________\///______________\////////////____\////////////_____\///______________
请按任意键继续. . .

**Comment by yuankaiwsl** [comment]
应该查询不出来“每周答题”得分了，可以check.py第75行内容改成'0'，76行：7改成6，77行8改成7。亲测。

**Comment by yuankaiwsl** [comment]
# 打印表格
    table.add_row(table_row[0],
                  table_row[1],
                  table_row[2],
                  table_row[3],
                  table_row[4],
                  table_row[5],
                  '0',
                  table_row[6] + '分',
                  table_row[7] + '分')

**Comment by Kobe-respect** [comment]
> 

可以分享一下吗

**Comment by casperzt** [comment]
能不能麻烦发一个附件到我的邮箱，万分感谢 casperzt@126.com

**Comment by akjybbs** [comment]
修改cheak,py文件中66-74行代码如下：
# 打印表格
    table.add_row(table_row[0],
                  table_row[1],
                  table_row[2],
                  table_row[3],
                  table_row[4],
                  table_row[5],
                  table_row[6] + '分',
                  table_row[7] + '分')
删除34行如下代码
    table.add_column("每周答题", justify='center')
删除93-95行如下三行代码
      if exam_temp['WEEKLY_EXAM'] == 'true' and settings['每周答题'] == 'true' and res == CheckResType.NULL and scores[5].text != '5分/5分':
        if settings['答题时间设置']['是否启用(关闭则每天都答题)'] != 'true' or (settings['答题时间设置']['是否启用(关闭则每天都答题)'] == 'true' and dayOfWeek in settings['答题时间设置']['答题类型(数字代表星期几)']['每周答题']):
            res = CheckResType.WEEKLY_EXAM

**Comment by LXT2017** [comment]
exe无法运行了，估计是查询出问题了，有没有新的exe

**Comment by x19870523** [comment]
能分享一个到我的邮箱吗？万分感谢 1288009@qq.com

**Comment by kenanadm2000** [comment]
能分享一个到我的邮箱吗？万分感谢 [173400@qq.com](mailto:173400@qq.com)

**Comment by paullu03** [comment]
> ```
> 修改cheak,py文件中66-74行代码如下：
> ```
> 
> # 打印表格
> ```
> table.add_row(table_row[0],
>               table_row[1],
>               table_row[2],
>               table_row[3],
>               table_row[4],
>               table_row[5],
>               table_row[6] + '分',
>               table_row[7] + '分')
> ```
> 
> 删除34行如下代码 table.add_column("每周答题", justify='center') 删除93-95行如下三行代码 if exam_temp['WEEKLY_EXAM'] == 'true' and settings['每周答题'] == 'true' and res == CheckResType.NULL and scores[5].text != '5分/5分': if settings['答题时间设置']['是否启用(关闭则每天都答题)'] != 'true' or (settings['答题时间设置']['是否启用(关闭则每天都答题)'] == 'true' and dayOfWeek in settings['答题时间设置']['答题类型(数字代表星期几)']['每周答题']): res = CheckResType.WEEKLY_EXAM

能分享一个到我的邮箱吗，谢谢了 253030599@qq.com

**Comment by junjuncc** [comment]
能分享一个到我的邮箱吗，谢谢了,kxxccc@qq.com

**Comment by applyapply** [comment]
> 能分享一个到我的邮箱吗？万分感谢 [36422072@qq.com]

**Comment by worthful99** [comment]
能分享一个到我的邮箱吗，万分感谢!!    xz2008cn@163.com

**Comment by worthful99** [comment]
> 能分享一个到我的邮箱吗，万分感谢!! [xz2008cn@163.com](mailto:xz2008cn@163.com)

**Comment by CNGMH** [comment]
可以分享到邮箱吗？万分感谢！2498151519@qq.com

**Comment by LossInWind** [comment]
能分享到我的邮箱吗，谢谢了,[2984263497@qq.com]
