### ISSUE TITLE
程序异常，脚本重启，不能得分

### ISSUE THREAD

**Issue by JQ453027964** [PRaichu/xxqg#94]
--> 当前ChromeDriver版本号和Chrome浏览器版本号不一致，准备进行更新
--> ChromeDriver下载成功
--> 解压成功
--> 压缩包已删除
--> ChromeDriver更新成功

--> 文章数据更新成功
--> 视频数据更新成功
--> 请在5分钟内扫码完成登录
--> 登录成功
Traceback (most recent call last):
  File "xuexi.py", line 136, in <module>
  File "xuexi.py", line 48, in run
  File "userOperation\check.py", line 77, in check_task
IndexError: list index out of range

--> 程序异常，请尝试重启脚本
--> 当前版本:1.0.9.2

**Comment by manburenshenglu** [comment]
遇到了同样的错误
